name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build - Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test - Run pytest
      run: |
        pytest tests/

    - name: Create and Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: midterm-calculator
        path: |
          *
          !.git/**
          !venv/** 